---
- hosts: all
  become: true
  tasks:
          - name: Add epel-release repo / Ensure it's up to date
            dnf:
              name: epel-release
              state: present

          - name: Install nginx package / Ensure it's up to date
            dnf: 
              name: nginx
              state: present

          - name: Ensure httpd service is stopped
            service:
              name: httpd
              state: stopped

          - name: Ensure nginx service is started
            service:
              name: nginx
              state: started
